[project]
name = "delivery-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.4",
    "django-vite>=3.1.0",
    "mysqlclient>=2.2.7",
]
