# Generated by Django 5.2.4 on 2025-07-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_map_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.IntegerField()),
                ('partner_id', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
