# Generated by Django 5.1.1 on 2025-07-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_map_app', '0002_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_map_app.user_table')),
            ],
        ),
    ]
