# Generated by Django 5.1.1 on 2025-07-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_map_app', '0003_location_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_name', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('date_of_delivery', models.DateField()),
                ('date_of_order', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_map_app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='order_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_person_id', models.IntegerField()),
                ('order_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_map_app.customer_order')),
            ],
        ),
    ]
