# Generated by Django 5.2.4 on 2025-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_map_app', '0003_remove_user_table_user_type_user_table_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='user_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
