# Generated by Django 5.2.4 on 2025-07-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_map_app', '0004_alter_user_table_partner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='password',
            field=models.TextField(),
        ),
    ]
