# Generated by Django 5.2.4 on 2025-07-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_map_app', '0005_alter_user_table_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='partner_id',
            field=models.TextField(null=True),
        ),
    ]
