# Generated by Django 5.2.4 on 2025-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_map_app', '0006_alter_user_table_partner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='partner_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
