# Generated by Django 5.2.4 on 2025-07-25 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_helper_app.user_types')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_helper_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='customer_order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_name', models.TextField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('date_of_delivery', models.DateField()),
                ('date_of_order', models.DateField()),
                ('order_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_helper_app.location')),
                ('assigned_delivery_agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='delivery_helper_app.profile')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='delivery_helper_app.profile')),
            ],
        ),
    ]
