# Generated by Django 5.1.1 on 2025-07-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_helper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_helper_app.profile'),
        ),
    ]
